# Generated by Django 4.2.23 on 2026-01-27 00:00

from django.db import migrations, models
import django.db.models.deletion
import payroll.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ca_allowances',
            field=models.IntegerField(default=0, help_text='Number of California state withholding allowances', validators=[payroll.models.models.min_zero], verbose_name='CA Allowances'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ca_filing_status',
            field=models.ForeignKey(blank=True, help_text='California state tax filing status for Method B calculation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ca_contracts', to='payroll.filingstatus', verbose_name='CA Filing Status'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='ca_allowances',
            field=models.IntegerField(default=0, help_text='Number of California state withholding allowances', validators=[payroll.models.models.min_zero], verbose_name='CA Allowances'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='ca_filing_status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='California state tax filing status for Method B calculation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.filingstatus', verbose_name='CA Filing Status'),
        ),
        migrations.AddField(
            model_name='historicalpayslip',
            name='tax_reporting_type',
            field=models.CharField(blank=True, choices=[('FIT', 'Federal Income Tax'), ('FICA_SS', 'Social Security Tax'), ('FICA_MED', 'Medicare Tax'), ('FUTA', 'Federal Unemployment Tax (FUTA)'), ('CA_PIT', 'CA Personal Income Tax'), ('CA_SDI', 'CA State Disability Insurance'), ('CA_ETT', 'CA Employment Training Tax'), ('CA_UI', 'CA Unemployment Insurance')], help_text='Explicitly map this deduction to a tax line on forms (941/940/DE9)', max_length=20, null=True, verbose_name='Tax Reporting Type'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_reporting_type',
            field=models.CharField(blank=True, choices=[('FIT', 'Federal Income Tax'), ('FICA_SS', 'Social Security Tax'), ('FICA_MED', 'Medicare Tax'), ('FUTA', 'Federal Unemployment Tax (FUTA)'), ('CA_PIT', 'CA Personal Income Tax'), ('CA_SDI', 'CA State Disability Insurance'), ('CA_ETT', 'CA Employment Training Tax'), ('CA_UI', 'CA Unemployment Insurance')], help_text='Explicitly map this deduction to a tax line on forms (941/940/DE9)', max_length=20, null=True, verbose_name='Tax Reporting Type'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='based_on',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic Pay'), ('gross_pay', 'Gross Pay'), ('taxable_gross_pay', 'Taxable Gross Pay'), ('net_pay', 'Net Pay'), ('ca_state_tax', 'California State Tax (Method B)'), ('federal_tax', 'US Federal Tax (2026)')], help_text='If the deduction is not fixed then specifies how the deduction provided', max_length=255, null=True),
        ),
    ]
