# Generated by Django 4.2.23 on 2026-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollsettings_tax_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='tax_reporting_type',
            field=models.CharField(blank=True, choices=[('FIT', 'Federal Income Tax'), ('FICA_SS', 'Social Security Tax'), ('FICA_MED', 'Medicare Tax'), ('FUTA', 'Federal Unemployment Tax (FUTA)'), ('CA_PIT', 'CA Personal Income Tax'), ('CA_SDI', 'CA State Disability Insurance'), ('CA_ETT', 'CA Employment Training Tax'), ('CA_UI', 'CA Unemployment Insurance')], help_text='Explicitly map this deduction to a tax line on forms (941/940/DE9)', max_length=20, null=True, verbose_name='Tax Reporting Type'),
        ),
    ]
